// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ZE9ICOa1ER2RW5_TMKfG0i6GZAC2DYY',
    appId: '1:80733184068:web:19da98e7c5a01c40969c11',
    messagingSenderId: '80733184068',
    projectId: 'waar-taxi',
    authDomain: 'waar-taxi.firebaseapp.com',
    storageBucket: 'waar-taxi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAqH3YolTryb9_uMYb1SwvDG-OYotafI',
    appId: '1:80733184068:android:049ca8ff9b2b10ca969c11',
    messagingSenderId: '80733184068',
    projectId: 'waar-taxi',
    storageBucket: 'waar-taxi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfx9w7JV5hvlFS8F2v65Ygq0wsnREXVuk',
    appId: '1:80733184068:ios:62ed109fc804ba3d969c11',
    messagingSenderId: '80733184068',
    projectId: 'waar-taxi',
    storageBucket: 'waar-taxi.firebasestorage.app',
    iosBundleId: 'com.example.dreverWarr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfx9w7JV5hvlFS8F2v65Ygq0wsnREXVuk',
    appId: '1:80733184068:ios:62ed109fc804ba3d969c11',
    messagingSenderId: '80733184068',
    projectId: 'waar-taxi',
    storageBucket: 'waar-taxi.firebasestorage.app',
    iosBundleId: 'com.example.dreverWarr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5ZE9ICOa1ER2RW5_TMKfG0i6GZAC2DYY',
    appId: '1:80733184068:web:02d3a2746466407f969c11',
    messagingSenderId: '80733184068',
    projectId: 'waar-taxi',
    authDomain: 'waar-taxi.firebaseapp.com',
    storageBucket: 'waar-taxi.firebasestorage.app',
  );
}
