import 'package:drever_warr/core/transleat/lunguesh_cubit.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class AppTranslations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      "phone_number": "Phone Number",
      "password": "Password",
      "forgot_password_question": "?Forgot Password",
      "login": "Login",
      "logout": "Logout",
      "logging_out":"Logging Out",
      "register_title": "Register",
      "full_name": "Name",
      "first_name": "First Name",
      "last_name":"Last Name",
      "Register": "Register",
      "phone_hint": "9xxxxxxxx",
      "governorate": "City",
      "select_governorate": "City",
      "enter_email": "Email",
      "enter_address": "Address",
      "emergency_number": "Emergency Number",
      "emergency_hint": "Alerts will be sent to this number",
      "gender": "Gender",
      "next": "Next",
      "no_data": "No data found",
      "error_occurred": "An error occurred",
      "validate_empty": "This field is required",
      "validate_phone": "Please enter a valid phone number",
      "validate_password": "Must be 8+ characters with uppercase, lowercase, number, and special character.",
      "male": "Male",
      "female": "Female",
      "enter_phone_reset_password":
          "Enter your mobile number to reset your password",
      "Send": "Send",
      "verification_title": "Verification",
      "reset_password_instruction":
          "Enter mobile number to set a new password.",
      "verification_title1": "Verify Phone Number",
      "verification_code_sent": "Verification code sent to",
      "enter_code_instruction": "Please enter the code sent to",
      "verify_identity": "verify your identity",
      "verify_button": "Verify",
      "resend_code": "Resend Code",
      "send_verification_code": "Send verification code",
      "resend_verification_code": "Resend verification code",
      "code_not_sent_question": "?Didn't receive the code",
      "new_password_title": "New Password",
      "enter_new_password_hint": "Enter new password",
      "confirm_password_label": "Confirm Password",
      "create_account_button": "Create Account",
      "welcome_trip_text": "?Ready to go... Where are we taking you today",
      "address_detail_request": "Please write your address in detail",
      "my_trips": "My Trips",
      "saved_locations": "Saved Locations",
      "settings": "Settings",
      "discount_codes": "Discount Codes",
      "technical_support": "Technical Support",
      "share_app": "Share App",
      "app_version": "Version",
      "saved_places": "Saved Places",
      "search_pickup": "Search pickup location",
      "search_destination": "Search destination",
      "confirm": "Confirm",
      "select_on_map": "Select on map",
      "confirm_location": "Confirm location",
      "note": "Note",
      "payment_methods": "Payment Methods",
      "pre_booking": "Pre-booking",
      "payment_available": ":Available payment methods",
      "cash": "Cash",
      "syriatel_cash": "Syriatel Cash",
      "cham_cash": "Cham Cash",
      "add_code": "Add Code",
      "selection_done": "Selection Done",
      "please_select_payment": "Please select a payment method",
      "order_notes_hint":
          "Write your notes about the order so the driver is aware of them",
      "done": "Done",
      "schedule_pre_order": "Schedule a pre-order",
      "add_promo_code": "Add promo code",
      "enter_promo_code": "Enter promo code here",
      "add": "Add",
      "use_before_trip": "To be used before the trip starts",
      "click_active_code": "Please click on one of the active codes",
      "add_new_favorite": "Add favorite location",
      "title": "Settings",
      "language": "Language",
      "arabic": "Arabic",
      "english": "English",
      "personal_info": "Personal Information",
      "sound_vibration": "Sound & Vibration",
      "location_permission": "Location Permissions",
      "enter_password_header": "Enter password to edit mobile number",
      "password_label": "Enter password",
      "enter_new_mobile_hint": "Enter new mobile number",
      "edit_mobile_number": "Edit mobile number",
      "trip_details": "Trip Details",
      "distance": ": Distance",
      "in_car_time": ": Time in car",
      "waiting_time": ": Waiting time",
      "client_name": ": Client Name",
      "invoice_details": ": Invoice Details",
      "trip_price": ": Trip Price",
      "discount": ": Discount",
      "total": ": Total",
      "admin_commission": ": Admin Commission",
      "payment_method": ": Payment Method",

      "your_rating": ": Your Rating",
      "excellent_trip": "Excellent trip.",
      "currency_syp": "SYP",
      "add_clear_profile_photo": "Add a clear profile photo",
      "take_photo_now": "Take a photo now",
      "add_front_id_photo": "Add a clear photo of the front of your ID",
      "add_back_id_photo": "Add a clear photo of the back of your ID",
      "create_account": "Create Account",
      "car_type": "Car Type",
      "car_model_year": "Car Model (Year)",
      "car_color": "Car Color",
      "add_car_photo": "Add a photo of the car",
      "add_plate_photo": "Add a photo of the car plate",
      "plate_number": "Plate Number",
      "category": "Category",
      "disclaimer":
          "The program is not responsible for any action, and the customer has no right to file any lawsuit against the program. Activation is not possible without agreeing to the terms and conditions.",
      "accept_terms": "I agree to the terms and conditions",
      "request_sent_waiting":
          "The driver request has been sent and is waiting for Admin review",
      "admin_review_status": "Admin review",
      "driver_name": "Driver Name",

      "orders": "Orders",
      "wallet": "Wallet",

      "my_profile": "My Profile",
      "feedback_complaints": "Feedback & Complaints",
      "finished_trips": "Finished Trips",
      "accept": "Accept",
      "urgent_orders": "Instant Orders",
  "scheduled_orders": "Scheduled Orders",
  "distances": "Distances",
    "km": "km",
    "rating": "Rating",
    "trips_count": "Total Trips",
    "reviews": "Reviews",
    "car_number": "Car Number",

    "phone": "Phone Number",
    "wallet_record": "Wallet Record",
    "current_balance": "Current Balance",
    "create_new_account": "Or create a new account",
      "transaction_to_account": "to your account.",
      "transaction_from_account": "from your account.",
      "transaction_sent": "Transferred ",
      "transaction_deducted": "Deducted ",
      "detecting_location": "Detecting your location...",
      "search_location_hint": "Search for a place or tap on the map",
      "confirm_location_continue": "Confirm location and \ncontinue registration",
      "save_changes": "Save Changes",
      "no_orders_now": "No orders available",
      "no_scheduled_orders_now": "No scheduled orders available",
      "error_loading_data": "Error while loading data",
      "default_client_name": "Wari Client",
      "no_phone": "No phone number",
      "currency_syp_short": "SYP",
      "distance_km": "km",
      "your_current_location": "Your current location",
      "passenger_location": "Passenger location",
      "trip_started": "Trip started",
      "start": "Start",
      "waiting_passenger_confirmation": "Waiting for passenger confirmation",
      "trip_finished_successfully": "Trip finished successfully",
      "end_trip": "End Trip",
      "emergency_sent": "Emergency signal sent!",
      "no_finished_trips": "No trips available",
      "distance_travelled": "Distance travelled",
      "time_spent": "Time spent",
      "waiting_time_label": "Waiting time",
      "driver": "Driver",
      "car_type_label": "Car type",
      "payment_method_label": "Payment method",
      "trip_rating": "Trip Rating",
      "write_your_opinion": "Write your opinion here...",
      "select_rating_warning": "Please select a star rating",
      "confirm_and_send_rating": "Confirm and send rating",
      "orders_summary": "There are {urgent} instant orders and {scheduled} scheduled orders",
      "accepted":"Accepted",
      "permission_denied_login_again": "Permission denied. You need to login again.",
      "general_retry_error": "Something went wrong. Check your internet connection and try again.",
      "failed_load_profile": "Failed to load profile data. Check your internet connection or server status.",
      "failed_load_wallet": "Failed to load wallet data. Check your internet connection or server status.",
      "redirecting_to_login_in": "Redirecting to login in {seconds} seconds...",
      "comments_and_complaints": "Comments and Complaints",
      "add_photo": "Add a photo",
      "choose_how_add_image": "Choose how you want to add the image",
      "gallery": "Gallery",
      "pick_image_from_device": "Pick an image from your device",
      "camera": "Camera",
      "take_new_picture": "Take a new picture",
      "complaint_photo_optional": "Add a complaints photo (optional, max 5 MB)",
      "tap_to_add_image": "Tap to add image",
      "photo_attached": "Photo attached",
      "send_complaint": "Send Complaint",
      "complaints_hint": "Complaints",
      "image_too_large": "Image must be 5 MB or smaller",
      "could_not_pick_image": "Could not pick the image",
      "please_write_your_complaint": "Please write your complaint",
      "select_car_category": "Select car category",
      "please_select_category": "Please select a category",
      "example_car_type": "e.g. Kia Rio",
      "example_car_year": "e.g. 2020",
      "id_upload_success": "Identity images uploaded successfully",
      "image_upload_success": "Image uploaded successfully",
      "trip_note": "Trip Note",
      "leave_app" : "? Do you want to leave the app",
      "work_not_saved" : "Your current work will not be saved unless you return",
      "leave": "Leave",
      "stay":"Stay",
      "current_trip":"Current Trips",
      "no_current_trip":"There are no Current Trips",
      "trips":"Journeys",
      "empty_filed" : "This Filed is Empty",
      "invalid_email" : "Invalid Email",
      "share_app_title": "Application Share For Waar",
      "share_app_description":
      "You can share the app link with your friends, or visit our website",
      "website": "Website",
      "share": "Share",
      "could_not_open_website": "Could not open website",
      "scheduled_date" : ": Trip Date"



    },
    'ar': {
      "distances": "المسافات",
    "km": "كم",
    "rating": "التقييم",
    "trips_count": "عدد الرحلات",
    "reviews": "الآراء",
    "car_number": "رقم السيارة",
    "car_type": "نوع السيارة",
    "phone": "رقم الهاتف",
      "urgent_orders": "الطلبات الفورية",
  "scheduled_orders": "الطلبات المجدولة",
      "accept": "قبول",
      "finished_trips": "الرحلات المنتهية",
      "driver_name": "اسم السائق",
      "my_trips": "رحلاتي",
      "orders": "الطلبات",
      "wallet": "الرصيد",
      "settings": "الإعدادات",
      "technical_support": "الدعم الفني",
      "my_profile": "بروفايلي",
      "feedback_complaints": "الملاحظات والشكاوي",
      "share_app": "مشاركة التطبيق",
      "app_version": "النسخة",
      "request_sent_waiting": " تم إرسال طلب السائق وبانتظار مراجعة الأدارة",
      "admin_review_status": "مراجعة الإدارة",
      "create_account": "إنشاء حساب",

      "car_model_year": "موديل (سنة) السيارة",
      "car_color": "لون السيارة",
      "add_car_photo": "أضف صورة للسيارة",
      "add_plate_photo": "أضف صورة للوحة السيارة",
      "plate_number": "نمرة السيارة",
      "category": "الفئة",
      "disclaimer":
          "إخلاء مسؤولية البرنامج من أي فعل ولا يحق للعميل رفع أي دعوى ضد البرنامج ولا يستطيع التفعيل بدون الموافقة على الأحكام والشروط.",
      "accept_terms": "الموافقة على الأحكام والشروط",

      "add_front_id_photo": "أضف صورة الهوية من الأمام بدقة واضحة",
      "add_back_id_photo": "أضف صورة الهوية من الخلف بدقة واضحة",
      "add_clear_profile_photo": "أضف صورتك الشخصية بدقة واضحة",
      "take_photo_now": "خذ صورة الآن",
      "trip_details": "تفاصيل الرحلة",
      "distance": ": المسافة",
      "in_car_time": ": وقت داخل السيارة",
      "waiting_time": ": وقت الانتظار",
      "client_name": ": اسم العميل",
      "invoice_details": ": تفاصيل الفاتورة",
      "trip_price": ": سعر الرحلة",
      "discount": ": الخصم",
      "total": ": المجموع",
      "admin_commission": ": عمولة الإدارة",
      "payment_method": ": طريقة الدفع",
      "cash": "نقداً",
      "your_rating": "تقييمك :",
      "excellent_trip": "الرحلة ممتازة.",
      "currency_syp": "ل.س",
      "enter_new_mobile_hint": "أدخل رقم الجوال الجديد",
      "edit_mobile_number": "تعديل رقم الجوال",
      "enter_password_header": "أدخل كلمة المرور لتعديل رقم الجوال",
      "password_label": "أدخل كلمة المرور",
      "title": "الإعدادات",
      "language": "اللغة",
      "arabic": "العربية",
      "english": "English",
      "personal_info": "معلوماتك الشخصية",
      "sound_vibration": "الصوت والاهتزاز",
      "location_permission": "صلاحيات الموقع",
      "add_new_favorite": "أضف موقع مفضل جديد",
      "enter_promo_code": "اكتب رمز كود الخصم هنا",
      "add": "إضافة",
      "use_before_trip": "لاستخدامها قبل بدء الرحلة",
      "click_active_code": "يرجى الضغط على أحد الأكواد المفعلة",
      "add_promo_code": "إضافة كود خصم",
      "schedule_pre_order": "جدولة طلب مسبق",
      "done": "تم",
      "order_notes_hint": "اكتب ملاحظاتك حول الطلب ليكون السائق على معرفة بها",
      "payment_available": ":طرق الدفع المتاحة",

      "syriatel_cash": "سيريتل كاش",
      "cham_cash": "شام كاش",
      "add_code": "أضف كود",
      "selection_done": "تم الاختيار",
      "please_select_payment": "يرجى اختيار طريقة الدفع",
      "note": "ملاحظة",
      "payment_methods": "طرق الدفع",
      "pre_booking": "الحجز المسبق",

      "confirm_location": "تأكيد المكان",
      "select_on_map": "حدد الموقع على الخريطة",
      "saved_places": "الأماكن المحفوظة",
      "search_pickup": "البحث عن عنوان الانطلاق",
      "search_destination": "البحث عن عنوان الوجهة",
      "confirm": "تأكيد",

      "saved_locations": "الأماكن المحفوظة",

      "discount_codes": "أكواد الخصم",

      "address_detail_request": "اكتب عنوانك بالتفصيل من فضلك",
      "welcome_trip_text": "جاهزون للانطلاق... إلى أين نأخذك اليوم؟",
      "Register": "انشاء حساب",
      "new_password_title": "كلمة سر جديدة",
      "enter_new_password_hint": "أدخل كلمة مرور جديدة",
      "confirm_password_label": "تأكيد كلمة المرور",
      "send_verification_code": "إرسال رمز التحقق",
      "resend_verification_code": "إعادة إرسال رمز التحقق",
      "code_not_sent_question": "لم يتم إرسال الرمز؟",
      "reset_password_instruction": "أدخل رقم الجوال لتعيين كلمة سر جديدة.",
      "verification_title": "التحقق من رقم الهاتف",
      "verification_code_sent": "تم إرسال رمز التحقق إلى الرقم",
      "enter_code_instruction": "يرجى إدخال رمز التحقق المرسل لنتمكن",
      "verify_identity": "من التحقق من هويتك",
      "verify_button": "تحقق",
      "resend_code": "إعادة إرسال الرمز",
      "verification_title1": "تحقق",
      "Send": "ارسال",
      "enter_phone_reset_password": "أدخل رقم الجوال لتعيين كلمة سر جديدة.",
      "male": "ذكر",
      "female": "أنثى",
      "login": "تسجيل الدخول",
      "logout":"تسجيل الخروج",
      "logging_out":"...يتم تسجيل الخروج",
      "phone_number": "الرقم",
      "password": "كلمة المرور",
      "forgot_password_question": "هل نسيت كلمة السر?",
      "register_title": "إنشاء حساب",
      "full_name": "الاسم",
      "first_name": "الاسم",
      "last_name": "الكنية",

      "phone_hint": "9xxxxxxxx",
      "governorate": "المدينة",
      "select_governorate": "المدينة",
      "enter_email": "الإيميل",
      "enter_address": "العنوان",
      "emergency_number": "رقم الطوارئ",
      "emergency_hint": "هذا الرقم سيتم توجيه التنبيهات إليه",
      "gender": "الجنس",
      "next": "التالي",
      "no_data": "لا توجد بيانات",
      "error_occurred": "حدث خطأ ما",
      "validate_empty": "هذا الحقل مطلوب",
      "validate_phone": "يرجى إدخال رقم هاتف صحيح",
      "validate_password": "يجب أن تتكوّن كلمة المرور من 8 أحرف على الأقل، وتحتوي على حرف كبير وصغير ورقم ورمز خاص.ً",
      "wallet_record": "سجل الرصيد",
      "current_balance": "رصيدك الحالي",
      "create_new_account": "او انشئ حساب جديد",
      "transaction_to_account": " إلى حسابك.",
      "transaction_from_account": " من حسابك.",
      "transaction_sent": "تم تحويل ",
      "transaction_deducted": "تم خصم ",
      "detecting_location": "جاري تحديد موقعك...",
      "search_location_hint": "ابحث عن موقعك أو انقر على الخريطة",
      "confirm_location_continue": "تأكيد الموقع ومتابعة التسجيل",
      "save_changes":"حفظ التغييرات",
      "no_orders_now": "لا يوجد طلبات حالياً",
      "no_scheduled_orders_now": "لا يوجد طلبات مجدولة حالياً",
      "error_loading_data": "حدث خطأ أثناء تحميل البيانات",
      "default_client_name": "عميل واري",
      "no_phone": "بدون رقم",
      "currency_syp_short": "ل.س",
      "distance_km": "كم",
      "your_current_location": "موقعك الحالي",
      "passenger_location": "موقع الراكب",
      "trip_started": "بدأت الرحلة",
      "start": "إنطلاق",
      "waiting_passenger_confirmation": "بانتظار تأكيد الراكب",
      "trip_finished_successfully": "تم إنهاء الرحلة بنجاح",
      "end_trip": "انتهت الرحلة",
      "emergency_sent": "تم إرسال إشارة الطوارئ!",
      "no_finished_trips": "لا يوجد رحلات حالية",
      "distance_travelled": "المسافة المقطوعة",
      "time_spent": "الوقت المستغرق",
      "waiting_time_label": "وقت الانتظار",
      "driver": "السائق",
      "car_type_label": "نوع السيارة",
      "payment_method_label": ": طريقة الدفع",
      "trip_rating": "تقييم الرحلة",
      "write_your_opinion": "اكتب رأيك هنا...",
      "select_rating_warning": "يرجى اختيار عدد النجوم للتقييم",
      "confirm_and_send_rating": "تأكيد وإرسال التقييم",
      "orders_summary": "هناك {urgent} طلبات فورية و {scheduled} طلبات مجدولة",
      "accepted":"مقبول",
      "permission_denied_login_again": "تم رفض الإذن. تحتاج إلى تسجيل الدخول مرة أخرى.",
      "general_retry_error": "حدث خطأ ما. تحقق من اتصال الإنترنت وحاول مرة أخرى.",
      "failed_load_profile": "فشل تحميل بيانات الملف الشخصي. تحقق من اتصال الإنترنت أو حالة الخادم.",
      "failed_load_wallet": "فشل تحميل بيانات الرصيد. تحقق من اتصال الإنترنت أو حالة الخادم.",
      "redirecting_to_login_in": "سيتم تحويلك إلى تسجيل الدخول خلال {seconds} ثوانٍ...",
      "comments_and_complaints": "الملاحظات والشكاوي",
      "add_photo": "إضافة صورة",
      "choose_how_add_image": "اختر طريقة إضافة الصورة",
      "gallery": "المعرض",
      "pick_image_from_device": "اختر صورة من جهازك",
      "camera": "الكاميرا",
      "take_new_picture": "التقاط صورة جديدة",
      "complaint_photo_optional": "أضف صورة للشكاوى (اختياري، بحد أقصى 5 ميغابايت)",
      "tap_to_add_image": "اضغط لإضافة صورة",
      "photo_attached": "تم إرفاق الصورة",
      "send_complaint": "إرسال الشكوى",
      "complaints_hint": "الشكاوى",
      "image_too_large": "يجب أن تكون الصورة 5 ميغابايت أو أقل",
      "could_not_pick_image": "تعذر اختيار الصورة",
      "please_write_your_complaint": "يرجى كتابة الشكوى",
      "select_car_category": "اختر فئة السيارة",
      "please_select_category": "يرجى اختيار الفئة",
      "example_car_type": "مثلاً: Kia Rio",
      "example_car_year": "مثلاً: 2020",
      "id_upload_success": "تم رفع صور الهوية بنجاح",
      "image_upload_success": "تم رفع الصورة بنجاح",
      "trip_note": "ملاحظات الرحلة",
      "leave_app" : "هل تريد مغادرة التطبيق؟",
      "work_not_saved" : "لن يتم حفظ عملك الحالي إلا إذا عدت.",
      "leave": "غادر",
      "stay":"البقاء",
      "current_trip":"الرحلات الحالية",
      "no_current_trip":"لايوجد رحلات حالية",
      "trips":"الرحلات",
      "empty_filed" : "يجب ملء الحقل",
      "invalid_email" : "الايميل خطأ",
      "share_app_title": "WAAR مشاركة تطبيق",
      "share_app_description":
      "يمكنك مشاركة رابط التطبيق مع أصدقائك، أو زيارة موقعنا الإلكتروني",
      "website": "الموقع",
      "share": "مشاركة",
      "could_not_open_website": "تعذر فتح الموقع الإلكتروني",
      "scheduled_date" : "موعد الرحلة : "



    },
    'ku': {
      "distances": "Dûrî",
      "km": "km",
      "rating": "Nirxandin",
      "trips_count": "Hejmara geştan",
      "reviews": "Dîtin",
      "car_number": "Hejmara erebeyê",
      "car_type": "Cureyê erebeyê",
      "phone": "Hejmara telefonê",
      "urgent_orders": "Daxwazên lezgîn",
      "scheduled_orders": "Daxwazên plankirî",
      "accept": "Qebûlkirin",
      "finished_trips": "Geştên bi dawî hatî",
      "driver_name": "Navê şofêr",
      "my_trips": "Geştên min",
      "orders": "Daxwaz",
      "wallet": "Balanse",
      "settings": "Sazkarî",
      "technical_support": "Piştgiriya teknîkî",
      "my_profile": "Profîla min",
      "feedback_complaints": "Têbînî û gilî",
      "share_app": "Serlêdanê parve bike",
      "app_version": "Guherto",
      "request_sent_waiting": "Daxwaza şofêr hat şandin û li benda nirxandina rêvebiriyê ye",
      "admin_review_status": "Nirxandina rêvebiriyê",
      "create_account": "Hesab çêbike",
      "car_model_year": "Modela (sala) erebeyê",
      "car_color": "Rengê erebeyê",
      "add_car_photo": "Wêneyê erebeyê lê zêde bike",
      "add_plate_photo": "Wêneyê plaqeya erebeyê lê zêde bike",
      "plate_number": "Hejmara plaqeyê",
      "category": "Kategorî",
      "disclaimer": "Berpirsiyariya bernameyê ji her kiryarekê tune ye û mafê xerîdar nîne ku dozekê li dijî bernameyê vebike.",
      "accept_terms": "Ez şert û mercan qebûl dikim",
      "add_front_id_photo": "Wêneyê nasnameyê yê pêş lê zêde bike",
      "add_back_id_photo": "Wêneyê nasnameyê yê paş lê zêde bike",
      "add_clear_profile_photo": "Wêneyekî profîlê yê zelal lê zêde bike",
      "take_photo_now": "Niha wêneyekî bikişîne",
      "trip_details": "Hûrguliyên geştê",
      "distance": "Dûrî:",
      "in_car_time": "Dema di erebeyê de:",
      "waiting_time": "Dema li benda manê:",
      "client_name": "Navê xerîdar:",
      "invoice_details": "Hûrguliyên fatûreyê:",
      "trip_price": "Bihayê geştê:",
      "discount": "Daxistin:",
      "total": "Kom:",
      "admin_commission": "Komîsyona rêvebiriyê:",
      "payment_method": "Rêbaza dravdanê:",
      "cash": "Kaxit (Cash)",
      "your_rating": "Nirxandina te:",
      "excellent_trip": "Geştek pir baş e.",
      "currency_syp": "S.P",
      "enter_new_mobile_hint": "Hejmara nû ya mobîlê binivîse",
      "edit_mobile_number": "Guhertina hejmara mobîlê",
      "enter_password_header": "Ji bo guhertina hejmarê şîfreyê binivîse",
      "password_label": "Şîfreyê binivîse",
      "title": "Sazkarî",
      "language": "Ziman",
      "arabic": "Erebî",
      "english": "Îngilîzî",
      "personal_info": "Agahiyên kesane",
      "sound_vibration": "Deng û lerizîn",
      "location_permission": "Destûrên cîh",
      "add_new_favorite": "Cîhekî bijare lê zêde bike",
      "enter_promo_code": "Koda daxistinê li vir binivîse",
      "add": "Zêde bike",
      "use_before_trip": "Berî destpêkirina geştê were bikaranîn",
      "click_active_code": "Ji kerema xwe li ser yek ji kodên çalak bitikîne",
      "add_promo_code": "Koda daxistinê lê zêde bike",
      "schedule_pre_order": "Daxwazek pêşwext plan bike",
      "done": "Temam",
      "order_notes_hint": "Têbîniyên xwe li ser daxwazê binivîse",
      "payment_available": "Rêbazên dravdanê yên berdest:",
      "syriatel_cash": "Syriatel Cash",
      "cham_cash": "Cham Cash",
      "add_code": "Kod lê zêde bike",
      "selection_done": "Hulbijartin qediya",
      "please_select_payment": "Ji kerema xwe rêbazek dravdanê hilbijêrin",
      "note": "Têbînî",
      "payment_methods": "Rêbazên dravdanê",
      "pre_booking": "Veqetandina pêşwext",
      "confirm_location": "Cîh piştrast bike",
      "select_on_map": "Li ser nexşeyê nîşan bike",
      "saved_places": "Cîhên tomarkirî",
      "search_pickup": "Li cîhê destpêkê bigere",
      "search_destination": "Li cîhê armancê bigere",
      "confirm": "Piştrast bike",
      "saved_locations": "Cîhên tomarkirî",
      "discount_codes": "Kodên daxistinê",
      "address_detail_request": "Ji kerema xwe navnîşana xwe bi berfirehî binivîse",
      "welcome_trip_text": "Em amade ne... Îro em te bibin ku derê?",
      "Register": "Hesab çêbike",
      "new_password_title": "Şîfreya nû",
      "enter_new_password_hint": "Şîfreyek nû binivîse",
      "confirm_password_label": "Şîfreyê piştrast bike",
      "send_verification_code": "Koda piştrastkirinê bişîne",
      "resend_verification_code": "Koda piştrastkirinê ji nû ve bişîne",
      "code_not_sent_question": "Kod nehat şandin?",
      "reset_password_instruction": "Ji bo şîfreyek nû hejmara mobîlê binivîse.",
      "verification_title": "Piştrastkirina hejmarê",
      "verification_code_sent": "Koda piştrastkirinê ji vê hejmarê re hat şandin",
      "enter_code_instruction": "Ji kerema xwe koda şandî binivîse",
      "verify_identity": "Nasnameya xwe piştrast bike",
      "verify_button": "Piştrast bike",
      "resend_code": "Kodê ji nû ve bişîne",
      "verification_title1": "Piştrast bike",
      "Send": "Bişîne",
      "enter_phone_reset_password": "Ji bo guhertina şîfreyê hejmarê binivîse.",
      "male": "Nêr",
      "female": "Mê",
      "login": "Têketin",
      "logout": "Derketin",
      "logging_out":"Derketin...",
      "phone_number": "Hejmar",
      "password": "Şîfre",
      "forgot_password_question": "Te şîfre ji bîr kiriye?",
      "register_title": "Hesab çêbike",
      "full_name": "Nav",
      "first_name": "Navê pêşî",
      "last_name": "Paşnav",
      "phone_hint": "9xxxxxxxx",
      "governorate": "Bajar",

      "select_governorate": "Bajar",
      "enter_email": "E-name",
      "enter_address": "Navnîşan",
      "emergency_number": "Hejmara hawarê",
      "emergency_hint": "Ev hejmar dê hişyariyan bistîne",
      "gender": "Zayend",
      "next": "Pêş de",
      "no_data": "Agahî nehat dîtin",
      "error_occurred": "Şaşiyek çêbû",
      "validate_empty": "Ev qad pêwîst e",
      "validate_phone": "Ji kerema xwe hejmarek rast binivîse",
      "validate_password": "Divê 8+ tîp hebe ku tîpên mezin, biçûk, hejmar û tîpek taybet dihewîne.",
      "wallet_record": "Siclê balansê",
      "current_balance": "Balansa te ya niha",
      "create_new_account": "An jî hesabek nû biafirîne",
      "transaction_to_account": " bo hesabê te.",
      "transaction_from_account": " ji hesabê te",
      "transaction_sent": "Hat veguhestin ",
      "transaction_deducted": "Hat kêmkirin ",
      "detecting_location": "Cîhê te tê diyarkirin...",
      "search_location_hint": "Li cîhekê bigere an li ser nexşeyê bitikîne",
      "confirm_location_continue": "Cîhê piştrast bike û berdewam bike",
      "save_changes": "Guhertinan Tomar Bike",
      "no_orders_now": "Niha daxwaz tune ne",
      "no_scheduled_orders_now": "Daxwazên plankirî tune ne",
      "error_loading_data": "Di barkirina daneyan de çewtî çêbû",
      "default_client_name": "Mişterî Wari",
      "no_phone": "Hejmar tune ye",
      "currency_syp_short": "S.P",
      "distance_km": "km",
      "your_current_location": "Cîhê te yê niha",
      "passenger_location": "Cîhê rêwiyan",
      "trip_started": "Geşt dest pê kir",
      "start": "Destpêkirin",
      "waiting_passenger_confirmation": "Li benda piştrastkirina rêwiyan",
      "trip_finished_successfully": "Geşt bi serketî qediya",
      "end_trip": "Geşt qediya",
      "emergency_sent": "Nîşana acîl hate şandin!",
      "no_finished_trips": "Tu geştên niha tune ne",
      "distance_travelled": "Dûrî ya hatî rêvekirin",
      "time_spent": "Demê hatî xerc kirin",
      "waiting_time_label": "Dema rawestanê",
      "driver": "Şofêr",
      "car_type_label": "Cureyê erebeyê",
      "payment_method_label": "Rêbaza dravdanê",
      "trip_rating": "Nirxandina geştê",
      "write_your_opinion": "Binerînê xwe li vir binivîse...",
      "select_rating_warning": "Ji kerema xwe hejmarek stêrkan hilbijêre",
      "confirm_and_send_rating": "Piştrast bike û nirxandin bişîne",
      "orders_summary": "Fermanên tavilê yên {scheduled} û fermanên plansazkirî yên {urgent} hene",
      "accepted":"Qebûl kirin",
      "permission_denied_login_again": "Destûr red kirin. Divê tu ji nû ve têkeve.",
      "general_retry_error": "Çewtiyek çêbû. Girêdana xwe ya înternetê kontrol bike û dîsa biceribîne.",
      "failed_load_profile": "Barkirina daneyên profîlê nebaş bû. Girêdana înternetê an rewşa serverê kontrol bike.",
      "failed_load_wallet": "Barkirina daneyên balanse nebaş bû. Girêdana înternetê an rewşa serverê kontrol bike.",
      "redirecting_to_login_in": "Di {seconds} çirkan de tê veguheztin bo têketinê...",
      "comments_and_complaints": "Têbînî û gilî",
      "add_photo": "Wêneyek lê zêde bike",
      "choose_how_add_image": "Hilbijêre tu çawa dixwazî wêneyê zêde bikî",
      "gallery": "Galeriya wêneyan",
      "pick_image_from_device": "Wêneyek ji amûra xwe hilbijêre",
      "camera": "Kamera",
      "take_new_picture": "Wêneyek nû bikişîne",
      "complaint_photo_optional": "Wêneyek ji bo gilîan lê zêde bike (dixwaze, herî zêde 5 MB)",
      "tap_to_add_image": "Ji bo zêdekirina wêneyê bitikîne",
      "photo_attached": "Wêne hat girêdan",
      "send_complaint": "Gilî bişîne",
      "complaints_hint": "Gilî",
      "image_too_large": "Divê wêne 5 MB an kêmtir be",
      "could_not_pick_image": "Wêne nehat hilbijartin",
      "please_write_your_complaint": "Ji kerema xwe gilî binivîse",
      "select_car_category": "Categoriya erebeyê hilbijêre",
      "please_select_category": "Ji kerema xwe kategorî hilbijêrin",
      "example_car_type": "mînak: Kia Rio",
      "example_car_year": "mînak: 2020",
      "id_upload_success": "Wêneyên nasnameyê serkeftî hatin barkirin",
      "image_upload_success": "Wêneyê serkeftî hat barkirin",
      "trip_note": "nota rêwîtiyê",
      "leave_app": "? Ma tu dixwazî ji sepanê derkevî",
      "work_not_saved": "Karê te yê niha nayê tomarkirin heke tu venegerî",
      "leave": "Derkeve",
      "stay": "Bimîne",
      "current_trip": "Rêwîtiyên niha",
      "There are no Current Trips": "Rêwîtiyên niha tune ne",
      "trips": "Rêwîtî",
      "empty_filed" : "Ev qada vala ye",
      "invalid_email" : "E-name nederbasdar e",
      "share_app_title": "Parvekirina serlêdana Waar",
      "share_app_description":
      "Tu dikarî girêdana serlêdanê bi hevalên xwe re parve bikî, an jî serdana malpera me bikî",
      "website": "Malper",
      "share": "Parve bike",
      "could_not_open_website": "Malper nehat vekirin",
      "scheduled_date" : ": Dîroka rêwîtiyê"


    },
  };

  static String _localeFromContext(BuildContext context) {
    final language = context.read<LanguageCubit>().state;

    if (language == Language.arabic) {
      return 'ar';
    } else if (language == Language.kurdish) {
      return 'ku';
    } else {
      return 'en';
    }
  }

  static String getStaticText(BuildContext context, String key) {
    final locale = _localeFromContext(context);
    return _localizedValues[locale]?[key] ?? key;
  }

  static String getText(BuildContext context, String key) {
    final locale = _localeFromContext(context);
    return _localizedValues[locale]?[key] ?? key;
  }
}
